import {lootEntries,debriefOptions} from '../shared/offworld/recovery.mjs?v=dialogue-doors-1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stage=id=>id.replace('stage-','').replaceAll('-',' ');
export function lootHtml(m,s){const rows=lootEntries(m,s);return `<h3>Loot · ${rows.filter(r=>r.collected).length} secured</h3>${rows.length?rows.map(r=>`<div class="loot-row"><strong>${esc(r.label)} ×${r.quantity}</strong><small>${esc(stage(r.stageId))} · ${r.status}</small></div>`).join(''):'<p class="muted">No loot discovered yet.</p>'}`;}
export function debriefHtml(m,s,capacity){
  const options=debriefOptions(m,s),saved=s.debrief?.confirmed;
  const list=(rows,kind)=>rows.length?rows.map(r=>`<label class="recovery-choice"><input type="checkbox" data-recovery="${kind}" data-cost="${r.cost??1}" value="${esc(r.instanceId)}" ${saved||!r.eligible?'disabled':''} ${s.debrief?.[kind==='holding'?'holdingIds':'receivingIds']?.includes(r.instanceId)?'checked':''}><span><strong>${esc(r.label)}${r.quantity?` ×${r.quantity}`:''}</strong><small>${esc(stage(r.stageId))}${r.state?` · ${r.state}`:''}${r.cost?` · ${r.cost} capacity`:''}${r.reason?` · ${esc(r.reason)}`:''}</small></span></label>`).join(''):'<p class="muted">None available.</p>';
  return `<h2>Mission debrief</h2><p>Party extracted at ${esc(s.sgcCurrentTime.slice(11,19))} UTC. Choose recovery destinations.</p><div class="recovery-columns"><section><h3>People → Holding</h3><p>${capacity?.HOLDING.free??"?"} / ${capacity?.HOLDING.total??"?"} slots free</p>${list(options.people.filter(r=>r.eligible),'holding')}</section><section><h3>Loot → Receiving</h3><p>${capacity?.RECEIVING.free??"?"} / ${capacity?.RECEIVING.total??"?"} inventory capacity free</p>${list(options.loot.filter(r=>r.eligible),'receiving')}</section></div><p class="muted">Selected assets are recovered along known secure routes to the Gate. Unselected loot and people stay at the site. Confirming reserves capacity in the saved base configuration. Edit rooms in the Room Simulator to change capacity.</p>${saved?'<p role="status">Recovery plan confirmed and included in mission results.</p>':'<p id="recoveryCapacity" role="status"></p><button id="confirmRecovery" class="primary">Confirm recovery</button>'}`;
}
