// Loaded only by the isolated smoke server's wrapper page.
const frame=document.querySelector('iframe'),delay=ms=>new Promise(r=>setTimeout(r,ms));
const assert=(value,message)=>{if(!value)throw Error(message);};
try{
 for(let n=0;n<150;n++){if(frame.contentDocument?.getElementById('status')?.textContent.startsWith('VALID'))break;await delay(100);}
 const w=frame.contentWindow,d=frame.contentDocument,$=id=>d.getElementById(id),exceptions=[];w.addEventListener('error',e=>exceptions.push(e.message));w.addEventListener('unhandledrejection',e=>exceptions.push(String(e.reason)));
 assert($('status').textContent.startsWith('VALID'),`Initial composition failed: ${$('status').textContent}`);
 const exports=[],OriginalBlob=w.Blob;w.Blob=class extends OriginalBlob{constructor(parts,options){super(parts,options);if(options?.type==='application/json')exports.push(parts.join(''));}};w.HTMLAnchorElement.prototype.click=function(){};
 $('export').click();const first=JSON.parse(exports[0]);assert(first.format==='mission-author-review-export-1'&&first.trace.decisions.length,'Draft/trace export missing');assert(first.readiness.status==='NOT_FINALIZED'&&first.readiness.summary.missingSourceReferences===0,'Readiness export missing or incorrect');assert($('review').textContent.includes('Finalizer readiness'),'Readiness not visible');
 $('requestForm').requestSubmit();$('export').click();assert(exports[0]===exports[1],'Repeat composition differs');
 $('seed').value='another-seed';$('seed').dispatchEvent(new w.Event('input'));assert($('export').disabled,'Stale export remained enabled');$('requestForm').requestSubmit();assert($('status').textContent.startsWith('VALID'),'Seed change failed');
 $('pattern').value='RECOVER';$('characterized').checked=true;$('requestForm').requestSubmit();assert($('status').textContent.startsWith('VALID'),'Recovery benchmark failed');assert($('review').textContent.includes('primary-device-recovery'),'Recovery intent missing');
 frame.style.width='390px';await delay(100);assert(w.innerWidth===390,'Mobile frame width wrong');assert(d.documentElement.scrollWidth<=390,'Mobile overflow');d.querySelector('details').open=true;assert(d.documentElement.scrollWidth<=390,'Expanded review overflows');
 $('export').click();const imported=JSON.parse(exports.at(-1)),originalCore=JSON.stringify(imported.draft.dynamic.information);imported.readiness={status:'PLAYABLE'};imported.draft.dynamic.events.push({possibilityId:'not-authored'});const transfer=new w.DataTransfer();transfer.items.add(new w.File([JSON.stringify(imported)],'draft.json',{type:'application/json'}));$('import').files=transfer.files;$('import').dispatchEvent(new w.Event('change'));
 for(let n=0;n<50;n++){if($('status').textContent.startsWith('REPAIRED'))break;await delay(100);}assert($('status').textContent.startsWith('REPAIRED'),'Imported optional choice not repaired');$('export').click();const repaired=JSON.parse(exports.at(-1));assert(repaired.repair.passes===1,'Repair pass count wrong');assert(JSON.stringify(repaired.draft.dynamic.information)===originalCore,'Repair changed core');
 assert(repaired.readiness.status==='NOT_FINALIZED','Imported readiness metadata trusted');$('seed').value='';$('requestForm').dispatchEvent(new w.Event('submit',{cancelable:true}));assert($('status').textContent.includes('nonempty seed')&&$('export').disabled,'Invalid request was not reported');assert(exceptions.length===0,JSON.stringify(exceptions));
 document.getElementById('outcome').textContent='Browser smoke passed';await fetch('/__smoke-result',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ok:true,checks:'compose, determinism, controls, export, import/repair, validation errors, 390px expanded layout',exceptions})});
}catch(error){document.getElementById('outcome').textContent=error.stack;await fetch('/__smoke-result',{method:'POST',body:JSON.stringify({ok:false,error:error.stack})});}
