export const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=value=>`<pre>${escape(JSON.stringify(value,null,2))}</pre>`;
const cards=rows=>`<div class="grid">${rows.join('')}</div>`;
export function renderReview(result){
 const warnings=result.trace?.warnings??[],audit=result.repair?.changes??[];
 let html=`<section><h2>Review status · ${escape(result.status)}</h2><p>${escape(result.reason??'Validated semantic intent. Execution and shared admission remain unresolved.')}</p>${warnings.length?`<details><summary>Authored-data gaps and unresolved behavior (${warnings.length})</summary><ul class="warning">${warnings.map(w=>`<li>${escape(w)}</li>`).join('')}</ul></details>`:''}${audit.length?`<details open><summary>Repair audit · one pass</summary>${json(audit)}</details>`:''}</section>`;
 if(result.draft){const {dynamic,opportunities,recoveryIntents,consequences}=result.draft,{information,incidents,events,complications}=dynamic,s=information.skeleton;
  html+=`<section><h2>Mission spine</h2><p>${escape(s.hookId)} → ${escape(s.patternId)} · ${s.stages.length} Stages · ${s.transitions.length} source transitions</p><ol>${s.objectives.map(o=>`<li>${escape(o.intent)} · ${escape(o.instanceId)} · ${escape(o.stageId)}${o.after.length?` · after ${escape(o.after.join(', '))}`:''}</li>`).join('')}</ol>${cards(s.stages.map(stage=>`<article class="card"><strong>${escape(stage.stageId)}</strong><p>${escape(stage.purposeIds.join(' / '))}</p><span class="tag">${escape(stage.environmentId)}</span></article>`))}<details><summary>Source graph and role placement</summary>${json({transitions:s.transitions,roles:s.roles})}</details></section>`;
  html+=`<section><h2>Facts and legitimate learning paths</h2>${cards(information.clues.map(c=>`<article class="card"><strong>${escape(c.factRoleId)}</strong><p>${escape(c.source.kind)} · ${escape(c.source.id)}</p><p class="muted">${escape(c.knowledgeId)} · access unresolved</p></article>`))}<details><summary>Author-only truth and interaction requirements</summary>${json({facts:information.facts,interactions:information.interactions,clues:information.clues,opportunityDerivation:information.opportunityDerivation})}</details></section>`;
  html+=`<section><h2>Dynamic possibilities</h2><p>${incidents.length} Incidents · ${events.length} Events · ${complications.length} complications</p><details><summary>Sources, lifecycle and conditional effects</summary>${json({incidents,events,complications})}</details></section>`;
  html+=`<section><h2>Recovery and consequences</h2><p>${opportunities.length} optional opportunities · ${recoveryIntents.length} recovery intents · ${consequences.length} unapplied consequences</p>${cards(recoveryIntents.map(r=>`<article class="card"><strong>${escape(r.instanceId)}</strong><p>${escape(r.recoveryRoleId)} → ${escape(r.destination)}</p><p class="muted">${r.handlingCost.value===null?'Cost unresolved':`${r.handlingCost.value} handling units · shared item definitions`}<br>Shared admission pending</p></article>`))}<details><summary>Identity, source methods and unapplied intent</summary>${json({opportunities,recoveryIntents,consequences})}</details></section>`;
 }
 if(result.readiness){const r=result.readiness;html+=`<section><h2>Finalizer readiness · ${escape(r.status)}</h2><p>${r.summary.sourceReferences} unique source references · ${r.summary.missingSourceReferences} missing sources · ${r.summary.unresolvedChecks} unresolved checks</p><ul class="warning">${r.blockers.map(b=>`<li>${escape(b)}</li>`).join('')}</ul>${r.rows.map(row=>`<details><summary>${escape(row.section)} · ${escape(row.id)}</summary>${json(row)}</details>`).join('')}</section>`;}
 const decisions=result.trace?.decisions??[];
 html+=`<section><h2>Selection trace</h2><p class="muted">Candidate compatibility and rejection reasons, before any execution.</p>${decisions.map(d=>`<details><summary>${escape(d.family)}${d.selectedId?` → ${escape(d.selectedId)}`:''}${d.candidates?` · ${d.candidates.filter(c=>c.reasons?.length).length} rejected`:''}</summary>${json(d)}</details>`).join('')}<details><summary>Reproducibility inputs</summary>${json(result.trace?.identity??{})}</details></section>`;
 return html;
}
